import { useLocation, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import {
  ArrowLeft,
  Download,
  Share2,
  CheckCircle,
  AlertCircle,
  TrendingUp,
  Mic,
  Clock,
  Calendar,
  Briefcase,
  ThumbsUp,
  ThumbsDown,
  Lightbulb,
  FileText,
  Printer,
  Copy,
  Award,
  XCircle,
  Target,
  Zap,
  Brain,
  BarChart3,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

export default function FeedbackPage() {
  const navigate = useNavigate();
  const location = useLocation();
  
  const [sessionData, setSessionData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("analysis");
  const [expandedQuestions, setExpandedQuestions] = useState({});

  useEffect(() => {
    if (location.state) {
      setSessionData(location.state);
    } else {
      setSessionData({
        date: new Date().toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        duration: "00:00",
        topic: "Unknown",
        score: 0,
        relevance: 0,
        fluency: 0,
        structure: 0,
        fillerWords: 0,
        strengths: ["No data available"],
        improvements: ["Please complete an interview session"],
        questions: [],
        allAnswers: [],
        passed: false,
      });
    }
    setLoading(false);
  }, [location.state]);

  const isPassed = (sessionData?.score || 0) > 50;
  const passStatus = isPassed ? "Passed" : "Failed";
  const passStatusColor = isPassed ? "text-emerald-600 bg-emerald-50" : "text-red-600 bg-red-50";
  const passStatusIcon = isPassed ? <Award className="w-5 h-5" /> : <XCircle className="w-5 h-5" />;

  const getScoreColor = (score) => {
    if (score >= 80) return "text-emerald-600";
    if (score >= 60) return "text-blue-600";
    if (score >= 50) return "text-yellow-600";
    return "text-red-600";
  };

  const getScoreBgColor = (score) => {
    if (score >= 80) return "bg-emerald-50";
    if (score >= 60) return "bg-blue-50";
    if (score >= 50) return "bg-yellow-50";
    return "bg-red-50";
  };

  const getScoreRingColor = (score) => {
    if (score >= 80) return "stroke-emerald-500";
    if (score >= 60) return "stroke-blue-500";
    if (score >= 50) return "stroke-yellow-500";
    return "stroke-red-500";
  };

  const getPerformanceLabel = (score) => {
    if (score >= 80) return "Excellent";
    if (score >= 70) return "Very Good";
    if (score >= 60) return "Good";
    if (score >= 50) return "Satisfactory";
    return "Needs Improvement";
  };

  const radius = 80;
  const circumference = 2 * Math.PI * radius;
  const progress = ((sessionData?.score || 0) / 100) * circumference;
  const offset = circumference - progress;

  const toggleQuestionExpand = (index) => {
    setExpandedQuestions(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const generateReportText = (data) => {
    const allAnswersList = data.allAnswers || data.questions || [];
    return `
╔══════════════════════════════════════════════════════════════╗
║              DEVMOCK INTERVIEW FEEDBACK REPORT               ║
╚══════════════════════════════════════════════════════════════╝

Date: ${data.date}
Duration: ${data.duration}
Topic: ${data.topic}
Status: ${data.score > 50 ? "PASSED ✓" : "FAILED ✗"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 OVERALL SCORE: ${data.score}/100

📈 BREAKDOWN:
   • Relevance: ${data.relevance}%
   • Fluency: ${data.fluency}%
   • Structure: ${data.structure}%
   • Filler Words: ${data.fillerWords}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💪 STRENGTHS:
${data.strengths?.map(s => `   • ${s}`).join('\n') || '   • None'}

🎯 AREAS FOR IMPROVEMENT:
${data.improvements?.map(i => `   • ${i}`).join('\n') || '   • None'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📝 DETAILED ANSWERS:
${allAnswersList.map((q, i) => `
Q${i + 1}: ${q.question}
Score: ${q.score || q.questionScore || 0}/100
Answer: ${q.answer || q.userAnswer}
${q.matchedKeywords?.length ? `Matched Keywords: ${q.matchedKeywords.join(', ')}` : ''}
${q.missingKeywords?.length ? `Missing Keywords: ${q.missingKeywords.join(', ')}` : ''}
`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 TIP: ${data.score > 50 
  ? "Keep practicing to maintain your performance level!"
  : "Focus on the key concepts and practice with the STAR method."}

Generated by DevMock - AI-Powered Interview Coach
    `;
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white flex flex-col">
        <Navbar />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p className="text-gray-600">Loading feedback...</p>
          </div>
        </div>
        <Footer />
      </div>
    );
  }

  if (!sessionData) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white flex flex-col">
        <Navbar />
        <div className="flex-1 flex items-center justify-center px-4">
          <div className="text-center max-w-md">
            <div className="text-6xl mb-4">📋</div>
            <h2 className="text-xl font-semibold text-gray-800 mb-2">No Feedback Data</h2>
            <p className="text-gray-600 mb-6">Please complete an interview session first.</p>
            <button
              onClick={() => navigate("/interviewlibrary")}
              className="px-6 py-2.5 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-xl hover:shadow-lg transition"
            >
              Go to Interview Library
            </button>
          </div>
        </div>
        <Footer />
      </div>
    );
  }

  const allQuestions = sessionData.allAnswers || sessionData.questions || [];

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white flex flex-col">
      <Navbar />

      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8 lg:py-10">
        {/* Header */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
          <button
            onClick={() => navigate("/interviewlibrary")}
            className="flex items-center gap-2 text-gray-600 hover:text-gray-900 transition-colors"
          >
            <ArrowLeft size={20} />
            <span className="text-sm font-medium hidden sm:inline">Back to Library</span>
          </button>
          
          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
              title="Print"
            >
              <Printer size={18} />
            </button>
            <button
              onClick={() => {
                navigator.clipboard.writeText(window.location.href);
                alert("Link copied to clipboard!");
              }}
              className="p-2 text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
              title="Copy Link"
            >
              <Copy size={18} />
            </button>
            <button
              onClick={() => {
                const reportContent = generateReportText(sessionData);
                const blob = new Blob([reportContent], { type: "text/plain" });
                const url = URL.createObjectURL(blob);
                const a = document.createElement("a");
                a.href = url;
                a.download = `interview-feedback-${sessionData.date}.txt`;
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="flex items-center gap-2 px-3 py-2 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-lg hover:shadow-md transition text-sm"
            >
              <Download size={16} />
              <span className="hidden sm:inline">Download Report</span>
            </button>
          </div>
        </div>

        {/* Session Info Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 sm:p-6 mb-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center gap-3 sm:gap-4">
              <div className={`p-2.5 sm:p-3 rounded-xl ${isPassed ? 'bg-emerald-50' : 'bg-red-50'}`}>
                <Briefcase className={`w-5 h-5 sm:w-6 sm:h-6 ${isPassed ? 'text-emerald-600' : 'text-red-600'}`} />
              </div>
              <div>
                <div className="flex flex-wrap items-center gap-2 sm:gap-3">
                  <h1 className="text-xl sm:text-2xl font-bold text-gray-900">Performance Analysis</h1>
                  <span className={`flex items-center gap-1 px-2 py-0.5 sm:px-3 sm:py-1 rounded-full text-xs sm:text-sm font-medium ${passStatusColor}`}>
                    {passStatusIcon}
                    <span>{passStatus}</span>
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-3 sm:gap-4 mt-1">
                  <div className="flex items-center gap-1 text-xs sm:text-sm text-gray-500">
                    <Calendar size={12} className="sm:w-4 sm:h-4" />
                    <span>{sessionData.date}</span>
                  </div>
                  <div className="flex items-center gap-1 text-xs sm:text-sm text-gray-500">
                    <Clock size={12} className="sm:w-4 sm:h-4" />
                    <span>{sessionData.duration}</span>
                  </div>
                  <div className="flex items-center gap-1 text-xs sm:text-sm text-gray-500">
                    <Briefcase size={12} className="sm:w-4 sm:h-4" />
                    <span className="capitalize">{sessionData.topic?.replace(/%20/g, ' ')}</span>
                  </div>
                </div>
              </div>
            </div>
            <button
              onClick={() => navigate(`/interview/${encodeURIComponent(sessionData.topic)}`)}
              className="px-3 py-1.5 sm:px-4 sm:py-2 border border-gray-200 rounded-lg text-xs sm:text-sm font-medium text-gray-700 hover:bg-gray-50 transition-colors"
            >
              Retake Interview
            </button>
          </div>
        </div>

        {/* Tabs - Scrollable on mobile */}
        <div className="flex gap-1 border-b border-gray-200 mb-6 overflow-x-auto pb-px">
          <button
            onClick={() => setActiveTab("analysis")}
            className={`px-4 sm:px-6 py-2.5 sm:py-3 text-sm font-medium transition-all relative whitespace-nowrap ${
              activeTab === "analysis"
                ? "text-blue-600"
                : "text-gray-500 hover:text-gray-700"
            }`}
          >
            Analysis
            {activeTab === "analysis" && (
              <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-600 rounded-full" />
            )}
          </button>
          <button
            onClick={() => setActiveTab("answers")}
            className={`px-4 sm:px-6 py-2.5 sm:py-3 text-sm font-medium transition-all relative whitespace-nowrap ${
              activeTab === "answers"
                ? "text-blue-600"
                : "text-gray-500 hover:text-gray-700"
            }`}
          >
            Your Answers
            {activeTab === "answers" && (
              <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-600 rounded-full" />
            )}
          </button>
          <button
            onClick={() => setActiveTab("insights")}
            className={`px-4 sm:px-6 py-2.5 sm:py-3 text-sm font-medium transition-all relative whitespace-nowrap ${
              activeTab === "insights"
                ? "text-blue-600"
                : "text-gray-500 hover:text-gray-700"
            }`}
          >
            Insights
            {activeTab === "insights" && (
              <div className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-600 rounded-full" />
            )}
          </button>
        </div>

        {/* Analysis Tab */}
        {activeTab === "analysis" && (
          <div className="space-y-6">
            {/* Overall Score Section */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 sm:p-6">
              <div className="flex flex-col lg:flex-row items-center gap-6 lg:gap-8">
                {/* Score Circle */}
                <div className="relative shrink-0">
                  <svg className="w-36 h-36 sm:w-44 sm:h-44 md:w-48 md:h-48" viewBox="0 0 200 200">
                    <circle
                      cx="100"
                      cy="100"
                      r={radius}
                      fill="none"
                      stroke="#e5e7eb"
                      strokeWidth="12"
                    />
                    <circle
                      cx="100"
                      cy="100"
                      r={radius}
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="12"
                      strokeLinecap="round"
                      className={getScoreRingColor(sessionData.score)}
                      strokeDasharray={circumference}
                      strokeDashoffset={offset}
                      transform="rotate(-90 100 100)"
                    />
                    <text
                      x="100"
                      y="90"
                      textAnchor="middle"
                      dominantBaseline="middle"
                      className="text-2xl sm:text-3xl font-bold fill-gray-900"
                    >
                      {sessionData.score}
                    </text>
                    <text
                      x="100"
                      y="115"
                      textAnchor="middle"
                      dominantBaseline="middle"
                      className="text-[10px] sm:text-xs fill-gray-500"
                    >
                      out of 100
                    </text>
                  </svg>
                </div>

                <div className="flex-1 text-center lg:text-left">
                  <div className="mb-3">
                    <h3 className={`text-lg sm:text-xl font-semibold mb-1 ${getScoreColor(sessionData.score)}`}>
                      {getPerformanceLabel(sessionData.score)}
                    </h3>
                    <p className="text-sm text-gray-500">
                      {isPassed 
                        ? "🎉 Congratulations! You've passed this interview assessment."
                        : "📚 Keep practicing! Review the feedback below to improve your score."}
                    </p>
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4">
                    <div className="bg-gray-50 rounded-lg p-2 sm:p-3">
                      <div className="flex justify-between text-xs sm:text-sm mb-1">
                        <span className="text-gray-600">Relevance</span>
                        <span className="font-medium text-gray-900">{sessionData.relevance}%</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-1.5 sm:h-2">
                        <div className="bg-emerald-500 rounded-full h-1.5 sm:h-2" style={{ width: `${sessionData.relevance}%` }} />
                      </div>
                    </div>
                    <div className="bg-gray-50 rounded-lg p-2 sm:p-3">
                      <div className="flex justify-between text-xs sm:text-sm mb-1">
                        <span className="text-gray-600">Fluency</span>
                        <span className="font-medium text-gray-900">{sessionData.fluency}%</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-1.5 sm:h-2">
                        <div className="bg-blue-500 rounded-full h-1.5 sm:h-2" style={{ width: `${sessionData.fluency}%` }} />
                      </div>
                    </div>
                    <div className="bg-gray-50 rounded-lg p-2 sm:p-3">
                      <div className="flex justify-between text-xs sm:text-sm mb-1">
                        <span className="text-gray-600">Structure</span>
                        <span className="font-medium text-gray-900">{sessionData.structure}%</span>
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-1.5 sm:h-2">
                        <div className="bg-purple-500 rounded-full h-1.5 sm:h-2" style={{ width: `${sessionData.structure}%` }} />
                      </div>
                    </div>
                  </div>

                  <div className="mt-3 p-2 sm:p-3 bg-gray-50 rounded-lg">
                    <p className="text-xs sm:text-sm text-gray-700">
                      {sessionData.fillerWords > 0 ? (
                        <>🎤 Detected <span className="font-semibold">{sessionData.fillerWords}</span> filler words. Try pausing instead of using "um" or "like".</>
                      ) : (
                        <>🎯 Excellent fluency with no filler words detected!</>
                      )}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Strengths & Improvements */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <div className="bg-emerald-50 rounded-2xl p-5 sm:p-6 border border-emerald-100">
                <div className="flex items-center gap-2 mb-4">
                  <ThumbsUp className="w-5 h-5 text-emerald-600" />
                  <h3 className="font-semibold text-emerald-800">Strengths</h3>
                </div>
                <ul className="space-y-3">
                  {sessionData.strengths?.map((strength, idx) => (
                    <li key={idx} className="flex gap-2 text-sm text-emerald-700">
                      <CheckCircle size={16} className="flex-shrink-0 mt-0.5" />
                      <span>{strength}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="bg-amber-50 rounded-2xl p-5 sm:p-6 border border-amber-100">
                <div className="flex items-center gap-2 mb-4">
                  <ThumbsDown className="w-5 h-5 text-amber-600" />
                  <h3 className="font-semibold text-amber-800">Areas to Improve</h3>
                </div>
                <ul className="space-y-3">
                  {sessionData.improvements?.map((improvement, idx) => (
                    <li key={idx} className="flex gap-2 text-sm text-amber-700">
                      <AlertCircle size={16} className="flex-shrink-0 mt-0.5" />
                      <span>{improvement}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Pro Tip */}
            <div className="bg-blue-50 rounded-2xl p-5 sm:p-6 border border-blue-100">
              <div className="flex items-start gap-3">
                <Lightbulb className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-medium text-blue-800 mb-1">Pro Tip</p>
                  <p className="text-sm text-blue-700">
                    Use the STAR method (Situation, Task, Action, Result) for behavioral questions. 
                    Your answers will be more structured and impactful. Aim for 60% to pass.
                  </p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Answers Tab - New! Shows all answers with scores */}
        {activeTab === "answers" && (
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            <div className="p-5 sm:p-6 border-b border-gray-100 bg-gray-50">
              <h2 className="text-lg font-semibold text-gray-900">Your Answers</h2>
              <p className="text-sm text-gray-500 mt-1">Review all your answers with detailed feedback</p>
            </div>
            
            <div className="divide-y divide-gray-100">
              {allQuestions.map((item, idx) => {
                const isExpanded = expandedQuestions[idx];
                const questionScore = item.score || item.questionScore || 0;
                
                return (
                  <div key={idx} className="p-5 sm:p-6">
                    <button
                      onClick={() => toggleQuestionExpand(idx)}
                      className="w-full text-left flex items-start justify-between gap-3"
                    >
                      <div className="flex-1">
                        <div className="flex flex-wrap items-center gap-2 mb-2">
                          <span className="text-xs font-medium text-gray-500">Question {idx + 1}</span>
                          <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getScoreBgColor(questionScore)} ${getScoreColor(questionScore)}`}>
                            Score: {questionScore}/100
                          </span>
                        </div>
                        <p className="text-sm sm:text-base font-medium text-gray-800">{item.question}</p>
                      </div>
                      {isExpanded ? (
                        <ChevronUp size={18} className="text-gray-400 flex-shrink-0" />
                      ) : (
                        <ChevronDown size={18} className="text-gray-400 flex-shrink-0" />
                      )}
                    </button>
                    
                    {isExpanded && (
                      <div className="mt-4 pt-4 border-t border-gray-100">
                        {/* User's Answer */}
                        <div className="mb-4">
                          <p className="text-xs font-medium text-blue-600 mb-1">Your Answer</p>
                          <div className="bg-blue-50 rounded-xl p-3 sm:p-4">
                            <p className="text-sm text-gray-700">{item.answer || item.userAnswer || "No answer provided"}</p>
                          </div>
                        </div>
                        
                        {/* Ideal Answer / Feedback */}
                        {item.feedback && (
                          <div className="mb-3">
                            <p className="text-xs font-medium text-green-600 mb-1">Feedback</p>
                            <p className="text-sm text-gray-600">{item.feedback}</p>
                          </div>
                        )}
                        
                        {/* Keywords */}
                        <div className="flex flex-wrap gap-2">
                          {item.matchedKeywords?.length > 0 && (
                            <div className="flex flex-wrap items-center gap-1">
                              <span className="text-xs text-emerald-600">✓ Matched:</span>
                              {item.matchedKeywords.map((kw, i) => (
                                <span key={i} className="text-xs bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded-full">{kw}</span>
                              ))}
                            </div>
                          )}
                          {item.missingKeywords?.length > 0 && (
                            <div className="flex flex-wrap items-center gap-1">
                              <span className="text-xs text-amber-600">⚠ Missing:</span>
                              {item.missingKeywords.map((kw, i) => (
                                <span key={i} className="text-xs bg-amber-50 text-amber-700 px-2 py-0.5 rounded-full">{kw}</span>
                              ))}
                            </div>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Insights Tab */}
        {activeTab === "insights" && (
          <div className="space-y-6">
            {/* Performance Metrics */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 sm:p-6">
              <div className="flex items-center gap-2 mb-5">
                <BarChart3 className="w-5 h-5 text-blue-600" />
                <h2 className="text-lg font-semibold text-gray-900">Performance Metrics</h2>
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                <div className="space-y-3">
                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-gray-600">Relevance</span>
                      <span className="font-medium text-gray-900">{sessionData.relevance}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div className="bg-emerald-500 rounded-full h-2" style={{ width: `${sessionData.relevance}%` }} />
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-gray-600">Fluency</span>
                      <span className="font-medium text-gray-900">{sessionData.fluency}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div className="bg-blue-500 rounded-full h-2" style={{ width: `${sessionData.fluency}%` }} />
                    </div>
                  </div>
                  <div>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-gray-600">Structure</span>
                      <span className="font-medium text-gray-900">{sessionData.structure}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div className="bg-purple-500 rounded-full h-2" style={{ width: `${sessionData.structure}%` }} />
                    </div>
                  </div>
                </div>
                
                <div className="bg-gray-50 rounded-xl p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Brain className="w-4 h-4 text-blue-600" />
                    <span className="text-xs font-semibold text-blue-700 uppercase">Key Takeaway</span>
                  </div>
                  <p className="text-sm text-gray-700">
                    {isPassed 
                      ? "Great job! Your response demonstrates good technical knowledge. Continue practicing to maintain this level."
                      : "Focus on addressing the key concepts and reducing filler words to improve your score."}
                  </p>
                </div>
              </div>
            </div>

            {/* Recommendations */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 sm:p-6">
              <div className="flex items-center gap-2 mb-5">
                <Zap className="w-5 h-5 text-amber-500" />
                <h2 className="text-lg font-semibold text-gray-900">Recommendations</h2>
              </div>
              
              <div className="space-y-3">
                <div className="flex gap-3 p-3 sm:p-4 bg-blue-50 rounded-xl">
                  <div className="w-7 h-7 sm:w-8 sm:h-8 bg-blue-600 rounded-lg flex items-center justify-center flex-shrink-0">
                    <Target size={14} className="text-white" />
                  </div>
                  <div>
                    <p className="font-medium text-gray-800 text-sm sm:text-base">Add Specific Metrics</p>
                    <p className="text-xs sm:text-sm text-gray-600 mt-0.5">
                      Quantify achievements with numbers. Instead of "made it faster," say 
                      "reduced processing time by 40%."
                    </p>
                  </div>
                </div>
                
                <div className="flex gap-3 p-3 sm:p-4 bg-emerald-50 rounded-xl">
                  <div className="w-7 h-7 sm:w-8 sm:h-8 bg-emerald-600 rounded-lg flex items-center justify-center flex-shrink-0">
                    <Mic size={14} className="text-white" />
                  </div>
                  <div>
                    <p className="font-medium text-gray-800 text-sm sm:text-base">Practice Pacing</p>
                    <p className="text-xs sm:text-sm text-gray-600 mt-0.5">
                      Slow down your speech. Pause between key points to let answers resonate.
                    </p>
                  </div>
                </div>
                
                {!isPassed && (
                  <div className="flex gap-3 p-3 sm:p-4 bg-amber-50 rounded-xl">
                    <div className="w-7 h-7 sm:w-8 sm:h-8 bg-amber-600 rounded-lg flex items-center justify-center flex-shrink-0">
                      <AlertCircle size={14} className="text-white" />
                    </div>
                    <div>
                      <p className="font-medium text-gray-800 text-sm sm:text-base">Review Core Concepts</p>
                      <p className="text-xs sm:text-sm text-gray-600 mt-0.5">
                        Focus on understanding key technical concepts. Practice explaining them clearly.
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div className="mt-8 flex flex-wrap gap-3 justify-between items-center">
          <button
            onClick={() => navigate("/interviewlibrary")}
            className="px-4 py-2.5 bg-gray-100 text-gray-700 rounded-xl font-medium hover:bg-gray-200 transition text-sm"
          >
            Try Another Interview
          </button>
          <div className="flex gap-3">
            <button
              onClick={() => window.print()}
              className="px-4 py-2.5 border border-gray-200 text-gray-700 rounded-xl font-medium hover:bg-gray-50 transition text-sm"
            >
              Save Feedback
            </button>
            <button
              onClick={() => navigate("/interviewlibrary")}
              className="px-4 py-2.5 bg-gradient-to-r from-blue-600 to-cyan-600 text-white rounded-xl font-medium hover:shadow-md transition text-sm"
            >
              Return to Library
            </button>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}